"""Shared utilities: configuration, enums, shift rota, exception hierarchy."""

from core.utilities.config_manager import ConfigManager
from core.utilities.enums import (
    CameraDriver,
    ConnectionState,
    DetectorType,
    InspectionResult,
    LogSource,
    PlcResultCode,
    TriggerMode,
    UserRole,
)
from core.utilities.shift_schedule import (
    DEFAULT_SHIFT_SPECS,
    Shift,
    ShiftSchedule,
    format_clock,
    parse_clock,
)
from core.utilities.exceptions import (
    AuthenticationError,
    CalibrationError,
    CameraCaptureError,
    CameraConfigurationError,
    CameraConnectionError,
    CameraError,
    ConfigurationError,
    DatabaseError,
    DetectionError,
    ExportError,
    PlcConnectionError,
    PlcError,
    PlcReadError,
    PlcTimeoutError,
    PlcWriteError,
    VisionSystemError,
)

__all__ = [
    "ConfigManager",
    "CameraDriver",
    "ConnectionState",
    "DetectorType",
    "InspectionResult",
    "LogSource",
    "PlcResultCode",
    "TriggerMode",
    "UserRole",
    "DEFAULT_SHIFT_SPECS",
    "Shift",
    "ShiftSchedule",
    "format_clock",
    "parse_clock",
    "AuthenticationError",
    "CalibrationError",
    "CameraCaptureError",
    "CameraConfigurationError",
    "CameraConnectionError",
    "CameraError",
    "ConfigurationError",
    "DatabaseError",
    "DetectionError",
    "ExportError",
    "PlcConnectionError",
    "PlcError",
    "PlcReadError",
    "PlcTimeoutError",
    "PlcWriteError",
    "VisionSystemError",
]
