"""Shared utilities: configuration, enums, exception hierarchy."""

from core.utilities.config_manager import ConfigManager
from core.utilities.enums import (
    CameraDriver,
    ConnectionState,
    DetectorType,
    InspectionResult,
    LogSource,
    PlcResultCode,
    TriggerMode,
    UserRole,
)
from core.utilities.exceptions import (
    AuthenticationError,
    CalibrationError,
    CameraCaptureError,
    CameraConfigurationError,
    CameraConnectionError,
    CameraError,
    ConfigurationError,
    DatabaseError,
    DetectionError,
    ExportError,
    PlcConnectionError,
    PlcError,
    PlcReadError,
    PlcTimeoutError,
    PlcWriteError,
    VisionSystemError,
)

__all__ = [
    "ConfigManager",
    "CameraDriver",
    "ConnectionState",
    "DetectorType",
    "InspectionResult",
    "LogSource",
    "PlcResultCode",
    "TriggerMode",
    "UserRole",
    "AuthenticationError",
    "CalibrationError",
    "CameraCaptureError",
    "CameraConfigurationError",
    "CameraConnectionError",
    "CameraError",
    "ConfigurationError",
    "DatabaseError",
    "DetectionError",
    "ExportError",
    "PlcConnectionError",
    "PlcError",
    "PlcReadError",
    "PlcTimeoutError",
    "PlcWriteError",
    "VisionSystemError",
]
